### ISSUE TITLE
配置后端的时候这个不太了解

### ISSUE THREAD

**Issue by Aruelius** [Ehco1996/shadowsocksr-deprecated#12]
![_20180722132303](https://user-images.githubusercontent.com/25380989/43042502-79fd0202-8db2-11e8-85a4-bf0dd7af6bd6.png)
这里第一个10050端口是在configs/user-config.json这个文件里修改的，原先是443，这个会影响什么么
还有就是我在前段修改的开始端口写的10050，但是新注册的用户都是随机给的端口，并不是从10050开始，而且只会重置端口也是随机的
还有就是，下面那些;stop server at port [3318] reason: port not exist
之类的报错是什么情况

**Comment by MikuShare** [comment]
哦对，这些问题都出在用数据库直连的时候，webapi是没问题的

**Comment by Ehco1996** [comment]
不推荐直连数据库的方式，已经不维护了
